apiVersion: apps/v1                                                                                                                               
kind: DaemonSet                                                                                                                                   
metadata:
  name: {{ include "spark.fullname" . }}-worker
  labels:
    app: spark-worker
spec:
  selector:
    matchLabels:
      name: spark-worker
  template:
    metadata:
      labels:
        name: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: bde2020/spark-worker:2.4.3-hadoop2.7
        imagePullPolicy: Always
        ports:
        - containerPort: 8081

