apiVersion: v1
kind: Service
metadata:
  name: spark-master
  labels:
{{ include "spark.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 7077
      targetPort: 7077 
      protocol: TCP
      name: master
    - port: 6066
      targetPort: 6066
      protocol: TCP
      name: master-rest
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "spark.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: spark-client
spec:
  selector:
    app: spark-client
  clusterIP: None

