apiVersion: v1
data:
  htpasswd: |+
    {{ .Values.registry.htpasswd_configmap.data }}

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Values.registry.htpasswd_configmap.name }}
  namespace: {{ .Values.registry.namespace }}

