apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.registry.pvc.name }}
  namespace: {{ .Values.registry.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.registry.pvc.size }}
