apiVersion: v1
data:
  tls.crt: {{ .Values.registry.tls.tls_cert }}
  tls.key: {{ .Values.registry.tls.tls_key }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Values.registry.tls.secret_name }}
  namespace: {{ .Values.registry.namespace }}
type: kubernetes.io/tls
