
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: grafana-role
  namespace: monitoring
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
    # Everything except secrets
    resources:
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]


---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: grafana-bind
  namespace: monitoring
roleRef:
  apiGroup: ""
  kind: Role
  name: grafana-role
subjects:
- kind: User
  name: grafana
  apiGroup: ""

