apiVersion: v1
kind: Pod
metadata:
  name: security-context-pod
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
  volumes:
  - name: sample-vol
    emptyDir: {}
  containers:
  - name: sample-container
    image: centos:latest
    command:
    - sleep
    - "10000"
    volumeMounts:
    - name: sample-vol
      mountPath: /mnt
    securityContext:
      allowPrivilegeEscalation: false
