apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hadoop.fullname" . }}-historyserver
  labels:
{{ include "hadoop.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-historyserver
      app.kubernetes.io/name: {{ include "hadoop.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: hadoop-historyserver
  template:
    metadata:
      labels:
        app: hadoop-historyserver
        app.kubernetes.io/name: {{ include "hadoop.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.images.historyserver }}"
          ports:
            - name: http
              containerPort: 8188
              protocol: TCP
          envFrom:
          - configMapRef:
              name: hadoop-env-config
          env:
          - name: "SERVICE_PRECONDITION"
            value: "hadoop-namenode:9870 hadoop-datanode:9864 hadoop-resourcemanager:8088"
          volumeMounts:
          - name: historyserver
            mountPath: /hadoop/yarn/timeline
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: historyserver
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
 #volumeClaimTemplates:
 # - metadata:
 #     name: historyserver
 #   spec:
 #     accessModes: [ "ReadWriteOnce" ]
 #     resources:
 #       requests:
 #         storage: {{ .Values.historyserver.storage }}

