apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode
  labels:
{{ include "hadoop.labels" . | indent 4 }}
spec:
  type: {{ .Values.services.type }}
  ports:
    - port: 9870
      targetPort: 9870
      protocol: TCP
      name: http
    - port: 8020
      targetPort: 8020
      protocol: TCP
      name: namenode
  selector:
    app: hadoop-namenode
  clusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: hadoop-resourcemanager
  labels:
{{ include "hadoop.labels" . | indent 4 }}
spec:
  type: {{ .Values.services.type }}
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: http
  selector:
    app: hadoop-resourcemanager
  clusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: hadoop-nodemanager
  labels:
{{ include "hadoop.labels" . | indent 4 }}
spec:
  type: {{ .Values.services.type }}
  ports:
    - port: 8042
      targetPort: 8042
      protocol: TCP
      name: http
  selector:
    app: hadoop-nodemanager
  clusterIP: None
---

apiVersion: v1
kind: Service
metadata:
  name: hadoop-historyserver
  labels:
{{ include "hadoop.labels" . | indent 4 }}
spec:
  type: {{ .Values.services.type }}
  ports:
    - port: 8188
      targetPort: 8188
      protocol: TCP
      name: http
  selector:
    app: hadoop-historyserver
  ClusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: hadoop-datanode
  labels:
{{ include "hadoop.labels" . | indent 4 }}
spec:
  type: {{ .Values.services.type }}
  ports:
    - port: 9864
      targetPort: 9864
      protocol: TCP
      name: http
  selector:
    app: hadoop-datanode
  ClusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: hadoop-journalnode
  labels:
{{ include "hadoop.labels" . | indent 4 }}
spec:
  type: {{ .Values.services.type }}
  ports:
    - port: 8485
      targetPort: 8485
      protocol: TCP
      name: http
  selector:
    app: hadoop-journalnode
  ClusterIP: None

