apiVersion: v1
kind: Service
metadata:
  name: node-zookeeper
  labels:
{{ include "kafka.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
      name: client
    - port: 2888
      targetPort: 2888
      protocol: TCP
      name: follower
    - port: 3888
      targetPort: 3888
      protocol: TCP
      name: election
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: admin
  selector:
    app: node-zookeeper
  clusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: node-kafka
  labels:
{{ include "kafka.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: client
    - port: 19092
      targetPort: 19092
      protocol: TCP
      name: follower
  selector:
    service: node-kafka
  clusterIP: None

