apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: some-namespace
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 0.5Gi
    limits.cpu: "1"
    limits.memory: 1Gi
    
---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: obejct-quota
  namespace: some-namespace
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "4"
    replicationcontrollers: "5"
    secrets: "10"
    services: "10"
    services.loadbalancers: "1"
