apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tick-stack.fullname" . }}-chronograf
  namespace: {{ .Values.namespace }}
  labels:
{{ include "tick-stack.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tick-stack.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      application: chronograf
  serviceName: chronograf-monitoring
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "tick-stack.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        application: chronograf
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-chronograf
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: chronograf
          imagePullPolicy: Always
          ports:
            - name: chronograf
              containerPort: 8888
              protocol: TCP
          env:
          - name: "INFLUXDB_URL"
            value: "http://influxdb-monitoring.monitoring:8086"
          - name: "KAPACITOR_URL"
            value: "http://kapacitor-monitoring.monitoring:9092"
          - name: "LOG_LEVEL"
            value: "error"
          - name: "REPORTING_DISABLED"
            value: "true"
          - name: "INFLUXDB_USERNAME"
            value: "{{ .Values.influx.admin_user }}"
          - name: "INFLUXDB_PASSWORD"
            value: "{{ .Values.influx.admin_password }}"
          resources:
            {{- toYaml .Values.chronograf_resources | nindent 12 }}
