apiVersion: v1
kind: Service
metadata:
  name: influxdb-monitoring
  namespace: {{ .Values.namespace }}
  labels:
{{ include "tick-stack.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: influx
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: influx2
  selector:
    application: influxdb


---

apiVersion: v1
kind: Service
metadata:
  name: chronograf-monitoring
  namespace: {{ .Values.namespace }}
  labels:
{{ include "tick-stack.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: chronograf
  selector:
    application: chronograf

---

apiVersion: v1
kind: Service
metadata:
  name: kapacitor-monitoring
  namespace: {{ .Values.namespace }}
  labels:
{{ include "tick-stack.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: kapacitor
  selector:
    application: kapacitor
  ClusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-monitoring
  namespace: {{ .Values.namespace }}
  labels:
{{ include "tick-stack.labels" . | indent 4 }}
{{- with .Values.grafana.service_annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: grafana
  selector:
    application: grafana

---

apiVersion: v1
kind: Service
metadata:
  name: telegraf-monitoring
  namespace: {{ .Values.namespace }}
  labels:
{{ include "tick-stack.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8186
      targetPort: 8186
      protocol: TCP
      name: telegraf
  selector:
    application: telegraf

