apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hadoop.fullname" . }}-namenode
  labels:
{{ include "hadoop.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-namenode
      app.kubernetes.io/name: {{ include "hadoop.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: hadoop-namenode
  template:
    metadata:
      labels:
        app: hadoop-namenode
        app.kubernetes.io/name: {{ include "hadoop.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.images.namenode }}"
          ports:
            - name: http
              containerPort: 9870
              protocol: TCP
            - name: namenode
              containerPort: 8020
              protocol: TCP
          envFrom:
          - configMapRef:
              name: hadoop-env-config
          env:
          - name: "CLUSTER_NAME"
            value: "{{ .Values.hadoop_env_config.cluster_name }}"
          volumeMounts:
          - name: namenode
            mountPath: /hadoop/dfs/name
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      volumes:
      - name: namenode
        persistentVolumeClaim:
          claimName: hadoop-namenode
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hadoop.fullname" . }}-resourcemanager
  labels:
{{ include "hadoop.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-resourcemanager
      app.kubernetes.io/name: {{ include "hadoop.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: hadoop-resourcemanager
  template:
    metadata:
      labels:
        app: hadoop-resourcemanager
        app.kubernetes.io/name: {{ include "hadoop.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.images.resourcemanager }}"
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
          envFrom:
          - configMapRef:
              name: hadoop-env-config
          env:
          - name: "SERVICE_PRECONDITION"
            value: "hadoop-namenode:9870 hadoop-datanode:9864"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hadoop.fullname" . }}-nodemanager
  labels:
{{ include "hadoop.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-nodemanager
      app.kubernetes.io/name: {{ include "hadoop.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: hadoop-nodemanager
  template:
    metadata:
      labels:
        app: hadoop-nodemanager
        app.kubernetes.io/name: {{ include "hadoop.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.images.nodemanager }}"
          ports:
            - name: http
              containerPort: 8042
              protocol: TCP
          envFrom:
          - configMapRef:
              name: hadoop-env-config
          env:
          - name: "SERVICE_PRECONDITION"
            value: "hadoop-namenode:9870 hadoop-datanode:9864 hadoop-resourcemanager:8088"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hadoop.fullname" . }}-historyserver
  labels:
{{ include "hadoop.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-historyserver
      app.kubernetes.io/name: {{ include "hadoop.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: hadoop-historyserver
  template:
    metadata:
      labels:
        app: hadoop-historyserver
        app.kubernetes.io/name: {{ include "hadoop.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.images.historyserver }}"
          ports:
            - name: http
              containerPort: 8188
              protocol: TCP
          envFrom:
          - configMapRef:
              name: hadoop-env-config
          env:
          - name: "SERVICE_PRECONDITION"
            value: "hadoop-namenode:9870 hadoop-datanode:9864 hadoop-resourcemanager:8088"
          volumeMounts:
          - name: historyserver
            mountPath: /hadoop/yarn/timeline
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      volumes:
      - name: historyserver
        persistentVolumeClaim:
          claimName: hadoop-historyserver
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

