{{- if .Values.ingress.enabled -}}
{{- $fullName := include "hadoop.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "hadoop.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.namenode_host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: hadoop-namenode
              servicePort: 9870
    - host: {{ .Values.ingress.historyserver_host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: hadoop-historyserver
              servicePort: 8188
{{- end }}

