apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-namenode
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.namenode_pvc_size }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-historyserver
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.historyserver_pvc_size }}
