apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""                ### Do not match any storage classes
  selector:                           ### Select volume based on labels
    matchLabels:
      app: elastic
