apiVersion: v1
kind: Pod
metadata:
  name: nfspvpod
  labels:
    name: nfspvpod
spec:
  containers:
  - name: nfspod
    image: cetnos:latest
    command:
    - sleep
    - "30000"
    volumeMounts:
    - name: nfspv
      mountPath: /mnt
  restartPolicy: Always
  securityContext:
    fsGroup: 65534            ## Needs to be the same as the nfs user and group on the nfs server
    runAsUser: 65534
  volumes:
  - name: nfspv
    persistenVolumeClaim:
      claimName: nfs-pvc
